'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class APIMonitor
    Public Property MonitorID As Integer
    Public Property UUID As String
    Public Property APIName As String
    Public Property CreatedDate As Date

End Class
