'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class APIOrderMedication
    Public Property APIOrderMedicationID As Integer
    Public Property APIOrderID_FK As Integer
    Public Property MedicationID As Nullable(Of Integer)
    Public Property MedicationName As String
    Public Property MedicationStatus As String
    Public Property MedicationQuantity As Nullable(Of Integer)
    Public Property MedicationQuantityUnit As String
    Public Property MedicationFrequencyID As Nullable(Of Integer)
    Public Property MedicationFrequency As Nullable(Of Integer)
    Public Property MedicationPeriod As Nullable(Of Integer)
    Public Property MedicationPeriodUnit As String
    Public Property MedicationAsNeeded As Nullable(Of Boolean)
    Public Property MedicationDisplay As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property DosageID_FK As Nullable(Of Integer)
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)

    Public Overridable Property APIOrder As APIOrder

End Class
