'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class APIOrderTask
    Public Property APIOrderTaskID As Integer
    Public Property APIOrderID_FK As Integer
    Public Property TaskID As Nullable(Of Integer)
    Public Property TaskName As String
    Public Property TaskTypeID As Nullable(Of Integer)
    Public Property TaskStartDateTime As Nullable(Of Date)
    Public Property TaskEndDateTime As Nullable(Of Date)
    Public Property TaskFrequencyID As Nullable(Of Integer)
    Public Property TaskFrequency As Nullable(Of Integer)
    Public Property TaskPeriod As Nullable(Of Integer)
    Public Property TaskPeriodUnit As String
    Public Property TaskDisplay As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property Remark As String

    Public Overridable Property APIOrder As APIOrder

End Class
