'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class APNSNotification
    Public Property Id As Integer
    Public Property NotificationMessage As String
    Public Property NotificationTitle As String
    Public Property UserID As Nullable(Of Integer)
    Public Property SentStatus As Nullable(Of Boolean)
    Public Property IsCritical As Nullable(Of Boolean)
    Public Property TaskID As Nullable(Of Integer)

End Class
