'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_BillingProposalService
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property BillingProposalServiceID As Integer
    Public Property BillingProposalID_FK As Integer
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property UnitCost As Decimal
    Public Property Duration1 As String
    Public Property Duration2 As String
    Public Property ServiceDescription As String
    Public Property Visit As Integer
    Public Property Session As Integer
    Public Property Discount As Decimal
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property SessionUsed As Integer
    Public Property ServiceID_FK As Integer

End Class
