'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_PatientMedicationConsume
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property PatientMedicationConsumeID As Integer
    Public Property PatientMedicationID_FK As Integer
    Public Property MedicationID_FK As Nullable(Of Integer)
    Public Property RouteID_FK As Nullable(Of Integer)
    Public Property DosageID_FK As Nullable(Of Integer)
    Public Property FrequencyID_FK As Nullable(Of Integer)
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Indication As String
    Public Property ReasonOfDiscontinue As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property ChronicDiseaseID_FK As Nullable(Of Integer)
    Public Property ChronicDiseaseSubInfoID_FK As Nullable(Of Integer)
    Public Property AcutePRNIndicationID_FK As Nullable(Of Integer)
    Public Property ReferID_FK As Nullable(Of Integer)
    Public Property InstructedByID_FK As Nullable(Of Integer)
    Public Property DrName As String
    Public Property DrContact As String
    Public Property MCRNo As String
    Public Property ClinicHosp As String
    Public Property InstructedBy2ID_FK As Nullable(Of Integer)
    Public Property DrNameED As String
    Public Property DrContactED As String
    Public Property MCRNoED As String
    Public Property ClinicHospED As String

End Class
