'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Item
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property ItemID As Integer
    Public Property ItemName As String
    Public Property CategoryID_FK As Integer
    Public Property ItemUnitID_FK As Integer
    Public Property Quantity As Integer
    Public Property UnitPrice As Decimal
    Public Property AvailableInBilling As Nullable(Of Boolean)
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

End Class
