'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_TreatmentListItem
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property TListItemID As Integer
    Public Property ItemName As String
    Public Property TListTypeID_FK As Integer
    Public Property IsActive As Nullable(Of Boolean)
    Public Property IsSystemUsed As Nullable(Of Boolean)
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property ItemBrand As String
    Public Property Cost As Nullable(Of Decimal)
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)

End Class
