'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_PatientProfile
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property PatientProfileID As Integer
    Public Property BloodTypeID_FK As Nullable(Of Integer)
    Public Property ReligionID_FK As Nullable(Of Integer)
    Public Property MobilePhone As String
    Public Property HomePhone As String
    Public Property Email As String
    Public Property BillingAddress1 As String
    Public Property BillingAddress2 As String
    Public Property BillingAddress3 As String
    Public Property BillingPostalCode As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property OtherReligion As String
    Public Property Organization As String
    Public Property Location As String
    Public Property Ward As String
    Public Property Bed As String
    Public Property Note As String
    Public Property PatientOrganizationID_FK As Nullable(Of Integer)

End Class
