'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_ReceiptForInvoice
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property ReceiptForInvoiceID As Integer
    Public Property ReceiptID_FK As Integer
    Public Property BillingInvoiceID_FK As Integer
    Public Property Amt As Decimal

End Class
