'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Types
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property code As String
    Public Property codeValue As String
    Public Property parentCode As String
    Public Property ordering As Integer
    Public Property created As Date
    Public Property updated As Nullable(Of Date)

End Class
