'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Users
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property UserId As Integer
    Public Property Email As String
    Public Property Password As String
    Public Property Firstname As String
    Public Property Lastname As String
    Public Property Remarks As String
    Public Property Photo As String
    Public Property Contact As String
    Public Property Designation As String
    Public Property Status As String
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property LastLoginDate As Nullable(Of Date)
    Public Property LastLogoutDate As Nullable(Of Date)
    Public Property LastActivityDate As Nullable(Of Date)
    Public Property LastLockoutDate As Nullable(Of Date)
    Public Property LastPasswordChangedDate As Nullable(Of Date)
    Public Property PreviousPasswords As String
    Public Property SessionKey As String
    Public Property ResetPassword As Nullable(Of Boolean)
    Public Property IsDeleted As Boolean
    Public Property LocationNow1 As String
    Public Property LocationNow2 As String
    Public Property LocationNow3 As String
    Public Property PostalCodeNow As String
    Public Property LocationNowModifiedDate As Nullable(Of Date)
    Public Property PatientID_FK As Nullable(Of Integer)
    Public Property IsExternal As Nullable(Of Boolean)
    Public Property UserOrganizationID_FK As Nullable(Of Integer)
    Public Property IsTCAccepted As Nullable(Of Boolean)
    Public Property UserName As String
    Public Property PreferredLanguage As Nullable(Of Integer)
    Public Property AccessLevelID_FK As Nullable(Of Integer)
    Public Property HasValidEmail As Boolean
    Public Property TokenID As String
    Public Property PreviousPasswords2 As String
    Public Property SharePdf As Nullable(Of Boolean)

End Class
