'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_PatientWoundVisit
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property PatientWoundVisitID As Integer
    Public Property PatientWoundID_FK As Integer
    Public Property VisitDate As Nullable(Of Date)
    Public Property WoundType As String
    Public Property WoundSubType As String
    Public Property WoundTypeOther As String
    Public Property SizeLength As Nullable(Of Decimal)
    Public Property SizeDepth As Nullable(Of Decimal)
    Public Property SizeWidth As Nullable(Of Decimal)
    Public Property Edges As String
    Public Property Appearance As String
    Public Property Smell As String
    Public Property UnderMining As String
    Public Property Exudate As String
    Public Property Suffering As Nullable(Of Integer)
    Public Property ImageUpload As String
    Public Property SurfaceArea As Nullable(Of Decimal)
    Public Property UnderMiningDepth As Nullable(Of Decimal)
    Public Property ExudateSubInfo As String
    Public Property VitalSignID_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property CareReportID_FK As Nullable(Of Integer)
    Public Property InitialCareAssessmentID_FK As Nullable(Of Integer)
    Public Property ReferID_FK As Nullable(Of Integer)
    Public Property NextReviewDate As Nullable(Of Date)
    Public Property TreatmentRemarks As String
    Public Property AssignedToID_FK As Nullable(Of Integer)
    Public Property DESIGN_R_Depth As String
    Public Property DESIGN_R_Exudate As Nullable(Of Integer)
    Public Property DESIGN_R_Size As Nullable(Of Integer)
    Public Property DESIGN_R_Inflammation As Nullable(Of Integer)
    Public Property DESIGN_R_Granulation As Nullable(Of Integer)
    Public Property DESIGN_R_Necrotic As Nullable(Of Integer)
    Public Property DESIGN_R_Pocket As Nullable(Of Integer)
    Public Property DESIGN_R_Score As Nullable(Of Integer)
    Public Property IsDESIGN_R As Nullable(Of Boolean)
    Public Property ExudateSubInfo2 As String
    Public Property PeriWound As String
    Public Property Debridement As String
    Public Property CleansingSolutionUsed As String
    Public Property Model_jpg As String
    Public Property Model_mtl As String
    Public Property Model_obj As String
    Public Property IsDraft As Nullable(Of Boolean)
    Public Property Volume As Nullable(Of Decimal)
    Public Property WoundInfection As Nullable(Of Boolean)
    Public Property fever As Nullable(Of Boolean)
    Public Property temperature As Nullable(Of Decimal)
    Public Property abscessPuss As Nullable(Of Boolean)
    Public Property increasedPain As Nullable(Of Boolean)
    Public Property erythema As Nullable(Of Boolean)
    Public Property oedema As Nullable(Of Boolean)
    Public Property localWarmth As Nullable(Of Boolean)
    Public Property increasedExcudate As Nullable(Of Boolean)
    Public Property delayedHealing As Nullable(Of Boolean)
    Public Property maladour As Nullable(Of Boolean)
    Public Property pocketing As Nullable(Of Boolean)
    Public Property suspectedInfection As Nullable(Of Boolean)
    Public Property TC_Granulation As Nullable(Of Decimal)
    Public Property TC_Slough As Nullable(Of Decimal)
    Public Property TC_Necrosis As Nullable(Of Decimal)
    Public Property TC_Epithelizing As Nullable(Of Decimal)
    Public Property TC_Others As Nullable(Of Decimal)
    Public Property TC_OriginalImage As String
    Public Property TC_WoundBedImage As String
    Public Property TC_AnnotatedImage As String
    Public Property TC_IsAccept As Nullable(Of Boolean)
    Public Property TC_Reason As String
    Public Property Perimeter As Nullable(Of Decimal)
    Public Property AverageDepth As Nullable(Of Decimal)
    Public Property MaximumDepth As Nullable(Of Decimal)
    Public Property MinimumDepth As Nullable(Of Decimal)
    Public Property IsRedness As Nullable(Of Boolean)
    Public Property IsSwelling As Nullable(Of Boolean)
    Public Property IsWarmToTouch As Nullable(Of Boolean)
    Public Property IsSmell As Nullable(Of Boolean)
    Public Property Size As Nullable(Of Decimal)
    Public Property TC_Auto_Granulation As Nullable(Of Decimal)
    Public Property TC_Auto_Slough As Nullable(Of Decimal)
    Public Property TC_Auto_Necrosis As Nullable(Of Decimal)
    Public Property TC_Auto_Epithelizing As Nullable(Of Decimal)
    Public Property TC_Auto_Others As Nullable(Of Decimal)
    Public Property NextTreatmentDate As Nullable(Of Date)
    Public Property InfectionRemarks As String
    Public Property TO_Comments As String
    Public Property DepthImage As String
    Public Property Status As String
    Public Property StatusRemark As String
    Public Property woundOverlaysImageDistance As Nullable(Of Decimal)
    Public Property woundOverlaysImage As String
    Public Property otherTissueName As String
    Public Property isTCAndImageModified As Nullable(Of Boolean)
    Public Property isTCModified As Nullable(Of Boolean)
    Public Property isWMModified As Nullable(Of Boolean)
    Public Property isUploadImageModified As Nullable(Of Boolean)
    Public Property ProgressiveWoundStage As String
    Public Property OriginalImageMeasurement As String
    Public Property WoundBedImageMeasurement As String
    Public Property DepthImageMeasurement As String
    Public Property AnnotatedImageMeasurement As String
    Public Property SizeLength_Auto As Nullable(Of Decimal)
    Public Property SizeDepth_Auto As Nullable(Of Decimal)
    Public Property SizeWidth_Auto As Nullable(Of Decimal)
    Public Property MeasurementUpdateRemark As String
    Public Property TCUpdateRemark As String
    Public Property DepthMax As Nullable(Of Decimal)
    Public Property DepthEighty As Nullable(Of Decimal)
    Public Property DepthSixty As Nullable(Of Decimal)
    Public Property DepthForty As Nullable(Of Decimal)
    Public Property DepthTwenty As Nullable(Of Decimal)
    Public Property DepthNegative As Nullable(Of Decimal)
    Public Property DepthNans As Nullable(Of Decimal)
    Public Property Rotation As Nullable(Of Decimal)
    Public Property Comments As String
    Public Property Title As String
    Public Property ReasonForChangeMeasurement As String
    Public Property ReasonForChangeClassification As String
    Public Property OrigWoundId As Nullable(Of Integer)
    Public Property SmallWound As Nullable(Of Boolean)
    Public Property FrequencyOfVisit As Nullable(Of Integer)

End Class
