'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Receipt
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property ReceiptID As Integer
    Public Property ReceiptNumber As String
    Public Property ReceiptDate As Date
    Public Property PatientID_FK As Integer
    Public Property PaymentModeID_FK As Integer
    Public Property TotalAmt As Decimal
    Public Property ReceivedFrom As String
    Public Property Remarks As String
    Public Property SendEmail As Nullable(Of Boolean)
    Public Property EmailPatient As Nullable(Of Boolean)
    Public Property EmailTo As String
    Public Property EmailCC As String
    Public Property EmailBCC As String
    Public Property CurrencyID_FK As Integer
    Public Property Status As String
    Public Property GroupNumber As String
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean

End Class
