'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_LoginDevice
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property LoginDeviceId As Integer
    Public Property UserId_FK As Integer
    Public Property DeviceType As String
    Public Property DeviceID As String
    Public Property CreatedDate As Date

End Class
