'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_EnquiryConfig
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property EnquiryConfigID As Integer
    Public Property SCMID_FK As Nullable(Of Integer)
    Public Property EmailContent As String
    Public Property EscalatingPersonID_FK As Nullable(Of Integer)
    Public Property EscalationPeriod As Nullable(Of Decimal)
    Public Property EscalationEmail As String
    Public Property EmailtoCMContent As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
