'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_VitalSignDetails
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property id As Integer
    Public Property vitalSignTypeId As Integer
    Public Property vitalSignId As Integer
    Public Property detailValue As Decimal
    Public Property IsDeleted As Boolean

End Class
