'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_PatientEBASDEPAnswer
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property PatientEBASDEPID_FK As Integer
    Public Property EBASDEPQuestionID_FK As Integer
    Public Property Answer As Nullable(Of Integer)

End Class
