'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_ProblemListGoal
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property ProblemListGoalID As Integer
    Public Property ProblemListID_FK As Integer
    Public Property Goal As String
    Public Property Action As Nullable(Of Integer)
    Public Property ScoreTypeID As Nullable(Of Integer)
    Public Property OperatorID As Nullable(Of Integer)

End Class
