'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Chat
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property ChatID As Integer
    Public Property Comment As String
    Public Property Attachment As String
    Public Property Attachment_Physical As String
    Public Property ParentID_FK As Nullable(Of Integer)
    Public Property PatientID_FK As Nullable(Of Integer)
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property IsDeleted As Boolean
    Public Property Family As Nullable(Of Boolean)

End Class
