'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_SysConfig
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property ConfigName As String
    Public Property ConfigValue As String
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsConfigurable As Nullable(Of Boolean)
    Public Property Description As String

End Class
