'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Code
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property CodeId As Integer
    Public Property CodeTypeId_FK As Integer
    Public Property CodeName As String
    Public Property Ordering As Nullable(Of Integer)
    Public Property IsSystemUsed As Boolean
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property Indication_Acute As Nullable(Of Boolean)
    Public Property Indication_PRN As Nullable(Of Boolean)
    Public Property Referral_Code As String
    Public Property AllergyReaction_Drug As Nullable(Of Boolean)
    Public Property AllergyReaction_Others As Nullable(Of Boolean)
    Public Property MedicationGroupID_FK As Nullable(Of Integer)
    Public Property Status As String
    Public Property CurrencyCodeA As String
    Public Property CurrencyCodeN As String
    Public Property CurrencyInvoiceFooter As String
    Public Property Critical As Nullable(Of Boolean)

End Class
