'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Disease
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property DiseaseID As Integer
    Public Property DiseaseName As String
    Public Property SystemID_FK As Integer
    Public Property IsAdditionalInfo As Boolean
    Public Property IsSuggestPalliativeCare As Boolean
    Public Property IsSystemUsed As Boolean
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property AdditionalInfo As String
    Public Property DiseaseCode As String

End Class
