'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Event
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property EventID As Integer
    Public Property EventName As String
    Public Property EventTypeID_FK As Integer
    Public Property PeriodTypeID_FK As Integer
    Public Property FromDate As Date
    Public Property ToDate As Date
    Public Property Remarks As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property UserCategory_FK As Nullable(Of Integer)

End Class
