'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_PatientSocialSupport
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property PatientSocialSupportID As Integer
    Public Property PatientID_FK As Nullable(Of Integer)
    Public Property InitialCareAssessmentID_FK As Nullable(Of Integer)
    Public Property Firstname As String
    Public Property Lastname As String
    Public Property GenderID_FK As Nullable(Of Integer)
    Public Property MaritalStatusID_FK As Nullable(Of Integer)
    Public Property RelationshipID_FK As Nullable(Of Integer)
    Public Property NationalityID_FK As Nullable(Of Integer)
    Public Property Contact As String
    Public Property Email As String
    Public Property NotifyEmail As Nullable(Of Boolean)
    Public Property NotifySMS As Nullable(Of Boolean)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property NotifyPhoneCall As Nullable(Of Boolean)
    Public Property Spokeperson As Nullable(Of Boolean)
    Public Property CanLogin As Nullable(Of Boolean)
    Public Property BillTo As Nullable(Of Boolean)
    Public Property UserType As String

End Class
