'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_MailSettings
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property id As Integer
    Public Property description As String
    Public Property msgBCC As String
    Public Property msgCC As String
    Public Property msgTo As String
    Public Property msgSubj As String
    Public Property msgBody As String
    Public Property displayMsgTo As Nullable(Of Boolean)
    Public Property displayMsgCC As Nullable(Of Boolean)
    Public Property displayMsgBCC As Nullable(Of Boolean)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean

End Class
