'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditTrail
    Public Property AuditTrailId As Integer
    Public Property AuditAction As String
    Public Property [Module] As String
    Public Property [Event] As String
    Public Property IPAddress As String
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property APIRequest As String

    Public Overridable Property Users As Users

End Class
