'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_NotificationChat
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property NotificationChatID As Integer
    Public Property NotificationId_FK As Integer
    Public Property ChatID_FK As Integer
    Public Property CreatedDate As Date
    Public Property ModifiedDate As Nullable(Of Date)

End Class
