'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Role
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property RoleId As Integer
    Public Property RoleDescription As String
    Public Property OptionText As String
    Public Property OptionValue As String
    Public Property OptionType As String
    Public Property Ordering As Integer
    Public Property DateCreated As Date
    Public Property Active As Nullable(Of Boolean)

End Class
