'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_CareReport
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property CareReportID As Integer
    Public Property PatientID_FK As Integer
    Public Property CareReportType As String
    Public Property Status As String
    Public Property SectionStatus As String
    Public Property Memo1 As String
    Public Property Memo2 As String
    Public Property Memo3 As String
    Public Property Memo4 As String
    Public Property Memo5 As String
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property CarePlanID_FK As Nullable(Of Integer)
    Public Property CareReportID_FK As Nullable(Of Integer)
    Public Property VisitStartDate As Nullable(Of Date)
    Public Property VisitEndDate As Nullable(Of Date)
    Public Property VisitedBy_FK As Nullable(Of Integer)
    Public Property Subject As String
    Public Property VitalSignID_FK As Nullable(Of Integer)
    Public Property Pain As String
    Public Property PainScaleType As String
    Public Property PainLevel As Nullable(Of Integer)
    Public Property PainDescriptionID_FK As Nullable(Of Integer)
    Public Property SiteOfPain As String
    Public Property TypeOfPain As String
    Public Property AggravatingFactor As String
    Public Property RelievingFactor As String
    Public Property Frequency As String
    Public Property PainRemarks As String
    Public Property NeuroOrMental As Nullable(Of Integer)
    Public Property Eyes As Nullable(Of Integer)
    Public Property VerbalResponse As Nullable(Of Integer)
    Public Property MotorResponse As Nullable(Of Integer)
    Public Property LeftEyeSize As Nullable(Of Integer)
    Public Property LeftEyeReaction As String
    Public Property RightEyeSize As Nullable(Of Integer)
    Public Property RightEyeReaction As String
    Public Property NeuroRemarks As String
    Public Property SectionRequired As String
    Public Property PsychoEmotionalSpiritual As String
    Public Property PsychoRemarks As String
    Public Property AirwayBreathingID_FK As Nullable(Of Integer)
    Public Property CoughID_FK As Nullable(Of Integer)
    Public Property O2AidID_FK As Nullable(Of Integer)
    Public Property O2LitresPercent As Nullable(Of Decimal)
    Public Property O2Litres As Nullable(Of Decimal)
    Public Property Sunction As String
    Public Property CoughAmount As String
    Public Property Color As String
    Public Property ColorOthers As String
    Public Property Consistency As String
    Public Property Nebuliser As String
    Public Property AirwayBreathingRemarks As String
    Public Property CirculationID_FK As Nullable(Of Integer)
    Public Property LowerEyelidsID_FK As Nullable(Of Integer)
    Public Property LipsID_FK As Nullable(Of Integer)
    Public Property CapillaryRefillID_FK As Nullable(Of Integer)
    Public Property PeripheralPulsesRadialID_FK As Nullable(Of Integer)
    Public Property PeripheralPulsesPedalID_FK As Nullable(Of Integer)
    Public Property CirculationRemarks As String
    Public Property SleepRestID_FK As Nullable(Of Integer)
    Public Property DayNightReversal As String
    Public Property SleepRestRemarks As String
    Public Property TemperatureID_FK As Nullable(Of Integer)
    Public Property TemperatureInterventions As String
    Public Property TemperatureRemarks As String
    Public Property BowelCareID_FK As Nullable(Of Integer)
    Public Property NoOfBowelTimes As Nullable(Of Integer)
    Public Property BowelType As Nullable(Of Integer)
    Public Property HowManyDaysBNO As Nullable(Of Integer)
    Public Property BowelInterventions As String
    Public Property Stoma As String
    Public Property StomaCreatedDate As Nullable(Of Date)
    Public Property StomaSizeLength As Nullable(Of Decimal)
    Public Property StomaSizeBreath As Nullable(Of Decimal)
    Public Property StomaColour As String
    Public Property StomaAppearance As String
    Public Property StomaProtrusion As String
    Public Property StomaPeristomalSkin As String
    Public Property StomaEffluent As String
    Public Property StomaAmountOfOutput As String
    Public Property StomaOstomyProductUsed As String
    Public Property StomaReviewDate As Nullable(Of Date)
    Public Property BowelRemarks As String
    Public Property BladderCareID_FK As Nullable(Of Integer)
    Public Property BladderCareTimes As Nullable(Of Integer)
    Public Property BladderCareNPU As Nullable(Of Integer)
    Public Property DiapersID_FK As Nullable(Of Integer)
    Public Property TypeOfUrine As String
    Public Property CharacteristicOfUrine As String
    Public Property Dysuria As String
    Public Property BladderCareRemarks As String
    Public Property PersonalHygieneRemarks As String
    Public Property CareReportRehabilitationID_FK As Nullable(Of Integer)
    Public Property EnvironmentRemarks As String
    Public Property ACP As Nullable(Of Boolean)
    Public Property ACP_DoneDate As Nullable(Of Date)
    Public Property ACP_ReviewDate As Nullable(Of Date)
    Public Property OtherTreatment As String
    Public Property OtherTreatmentOther As String
    Public Property OtherTreatmentRemarks As String
    Public Property CareReportSystemInfoID_FK As Nullable(Of Integer)
    Public Property SectionRequireInput As String
    Public Property PatientNutritionID_FK As Nullable(Of Integer)
    Public Property SkinAndWoundCare As String
    Public Property PersonalHygiene As String
    Public Property Environment As String
    Public Property BreathSounds As String
    Public Property BowelSounds As String
    Public Property HeartSounds As String

End Class
