'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_RegisteredDeviceV2
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property RegisteredDeviceID As Integer
    Public Property UserId_FK As Nullable(Of Integer)
    Public Property DeviceId As String
    Public Property DeviceName As String
    Public Property DeviceType As String
    Public Property DeviceToken As String
    Public Property FirstRegisterIpAddress As String
    Public Property Status As String
    Public Property Remarks As String
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property AppName As String
    Public Property Version As String

End Class
