'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit_Thresholds
    Public Property AuditAction As String
    Public Property ActionTime As Date
    Public Property id As Integer
    Public Property name As String
    Public Property minValue As Decimal
    Public Property maxValue As Decimal
    Public Property isDeleted As Boolean
    Public Property createdBy As Nullable(Of Integer)
    Public Property createdDate As Date
    Public Property updatedBy As Nullable(Of Integer)
    Public Property updatedDate As Nullable(Of Date)
    Public Property ews_min_1 As Nullable(Of Decimal)
    Public Property ews_max_1 As Nullable(Of Decimal)
    Public Property ews_min_2 As Nullable(Of Decimal)
    Public Property ews_max_2 As Nullable(Of Decimal)
    Public Property ews_min_3 As Nullable(Of Decimal)
    Public Property ews_max_3 As Nullable(Of Decimal)
    Public Property ews_min_4 As Nullable(Of Decimal)
    Public Property ews_max_4 As Nullable(Of Decimal)
    Public Property ews_min_5 As Nullable(Of Decimal)
    Public Property ews_max_5 As Nullable(Of Decimal)
    Public Property ews_min_6 As Nullable(Of Decimal)
    Public Property ews_max_6 As Nullable(Of Decimal)
    Public Property ews_min_7 As Nullable(Of Decimal)
    Public Property ews_max_7 As Nullable(Of Decimal)

End Class
