'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BillingPackageRequest
    Public Property PackageRequestID As Integer
    Public Property PackageRequestNo As String
    Public Property PatientID_FK As Integer
    Public Property PatientName As String
    Public Property SendBillTo As String
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Discount As Boolean
    Public Property DiscountType As String
    Public Property DiscountAmt As Decimal
    Public Property DiscountPercentage As Decimal
    Public Property Remarks As String
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property BillingAddress1 As String
    Public Property BillingAddress2 As String
    Public Property BillingAddress3 As String
    Public Property BillingPostalCode As String
    Public Property TotalPackageAmount As Decimal
    Public Property Email As String
    Public Property PackageList As String

End Class
