'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BillingProposal
    Public Property BillingProposalID As Integer
    Public Property PatientID_FK As Integer
    Public Property ProposalNumber As String
    Public Property Title As String
    Public Property SendEmail As Nullable(Of Boolean)
    Public Property EmailPatient As Nullable(Of Boolean)
    Public Property EmailTo As String
    Public Property EmailCC As String
    Public Property EmailBCC As String
    Public Property CurrencyID_FK As Integer
    Public Property TotalCost As Decimal
    Public Property Status As String
    Public Property GroupNumber As String
    Public Property Version As Short
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property ProposalType As String

    Public Overridable Property BillingInvoiceService As ICollection(Of BillingInvoiceService) = New HashSet(Of BillingInvoiceService)
    Public Overridable Property Code As Code
    Public Overridable Property Patient As Patient
    Public Overridable Property Users As Users
    Public Overridable Property Users1 As Users
    Public Overridable Property BillingProposalService As ICollection(Of BillingProposalService) = New HashSet(Of BillingProposalService)

End Class
