'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class C4WImage
    Public Property C4WImageId As Integer
    Public Property WoundImageName As String
    Public Property WoundImageData As String
    Public Property WoundBedImageName As String
    Public Property WoundBedImageData As String
    Public Property TissueImageName As String
    Public Property TissueImageData As String
    Public Property DepthImageName As String
    Public Property DepthImageData As String
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

End Class
