'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CareReportRehabilitation
    Public Property CareReportRehabilitationID As Integer
    Public Property IsADLAssistance As Nullable(Of Boolean)
    Public Property ADLAssistanceType As String
    Public Property Bounded As String
    Public Property NoOfTimesTurned As Nullable(Of Integer)
    Public Property NoOfSatOutOfBed As Nullable(Of Integer)
    Public Property IsDVTPrevention As Nullable(Of Boolean)
    Public Property DVTType As String
    Public Property RequirePhysioTherapist As Nullable(Of Boolean)
    Public Property VisitForPhysioTherapist As Nullable(Of Integer)
    Public Property RequireOccupationTherapist As Nullable(Of Boolean)
    Public Property VisitForOccupationTherapist As Nullable(Of Integer)
    Public Property RequireSpeechTherapist As Nullable(Of Boolean)
    Public Property VisitForSpeechTherapist As Nullable(Of Integer)
    Public Property RequireWalkingAid As Nullable(Of Boolean)
    Public Property WalkingAidType As String
    Public Property IsUpperLimbStrengthLeft As Nullable(Of Boolean)
    Public Property IsUpperLimbStrengthRight As Nullable(Of Boolean)
    Public Property UpperLimbStrengthLeft As Nullable(Of Integer)
    Public Property UpperLimbStrengthRight As Nullable(Of Integer)
    Public Property IsLowerLimbStrengthLeft As Nullable(Of Boolean)
    Public Property IsLowerLimbStrengthRight As Nullable(Of Boolean)
    Public Property LowerLimbStrengthLeft As Nullable(Of Integer)
    Public Property LowerLimbStrengthRight As Nullable(Of Integer)
    Public Property RehabilitationRemarks As String
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

    Public Overridable Property CareReport As ICollection(Of CareReport) = New HashSet(Of CareReport)

End Class
