'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CarePlanDetail
    Public Property CarePlanDetailID As Integer
    Public Property CarePlanSubID_FK As Integer
    Public Property SystemID_FK As Integer
    Public Property DiseaseID_FK As Integer
    Public Property DiseaseSubInfoID_FK As Nullable(Of Integer)

    Public Overridable Property CarePlanSub As CarePlanSub
    Public Overridable Property Disease As Disease
    Public Overridable Property SystemForDisease As SystemForDisease

End Class
