'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CarePlanSub
    Public Property CarePlanSubID As Integer
    Public Property CarePlanID_FK As Integer
    Public Property SubCarePlanName As Integer
    Public Property Goal As String
    Public Property ReviewDate As Nullable(Of Date)
    Public Property PersonInCharge As Nullable(Of Integer)
    Public Property ApprovedDate As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)
    Public Property GroupCode As Nullable(Of Integer)
    Public Property CarePlanGroupName As String
    Public Property DiseaseID_FK As Nullable(Of Integer)
    Public Property InterventionStatus As String
    Public Property GoalStatus As String

    Public Overridable Property CarePlan As CarePlan
    Public Overridable Property CarePlanDetail As ICollection(Of CarePlanDetail) = New HashSet(Of CarePlanDetail)
    Public Overridable Property CarePlanSubGoal As ICollection(Of CarePlanSubGoal) = New HashSet(Of CarePlanSubGoal)
    Public Overridable Property CarePlanSubProblemList As ICollection(Of CarePlanSubProblemList) = New HashSet(Of CarePlanSubProblemList)
    Public Overridable Property Activity As ICollection(Of Activity) = New HashSet(Of Activity)
    Public Overridable Property CPGoals As ICollection(Of CPGoals) = New HashSet(Of CPGoals)
    Public Overridable Property Intervention As ICollection(Of Intervention) = New HashSet(Of Intervention)

End Class
