'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Disease
    Public Property DiseaseID As Integer
    Public Property DiseaseName As String
    Public Property SystemID_FK As Integer
    Public Property IsAdditionalInfo As Boolean
    Public Property IsSuggestPalliativeCare As Boolean
    Public Property IsSystemUsed As Boolean
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property AdditionalInfo As String
    Public Property DiseaseCode As String

    Public Overridable Property Activity As ICollection(Of Activity) = New HashSet(Of Activity)
    Public Overridable Property CarePlanDetail As ICollection(Of CarePlanDetail) = New HashSet(Of CarePlanDetail)
    Public Overridable Property CarePlanSubGoal As ICollection(Of CarePlanSubGoal) = New HashSet(Of CarePlanSubGoal)
    Public Overridable Property CPGoals As ICollection(Of CPGoals) = New HashSet(Of CPGoals)
    Public Overridable Property SystemForDisease As SystemForDisease
    Public Overridable Property DiseaseInfo As ICollection(Of DiseaseInfo) = New HashSet(Of DiseaseInfo)
    Public Overridable Property DiseaseSubInfo As ICollection(Of DiseaseSubInfo) = New HashSet(Of DiseaseSubInfo)
    Public Overridable Property DiseaseVitalSignType As ICollection(Of DiseaseVitalSignType) = New HashSet(Of DiseaseVitalSignType)
    Public Overridable Property Intervention As ICollection(Of Intervention) = New HashSet(Of Intervention)
    Public Overridable Property PatientClinician As ICollection(Of PatientClinician) = New HashSet(Of PatientClinician)
    Public Overridable Property PatientFamilyHistory As ICollection(Of PatientFamilyHistory) = New HashSet(Of PatientFamilyHistory)
    Public Overridable Property PatientMedicationConsume As ICollection(Of PatientMedicationConsume) = New HashSet(Of PatientMedicationConsume)
    Public Overridable Property ProblemList As ICollection(Of ProblemList) = New HashSet(Of ProblemList)

End Class
