'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailLog
    Public Property EmailLogId As Integer
    Public Property description As String
    Public Property msgBCC As String
    Public Property msgCC As String
    Public Property msgTo As String
    Public Property msgSubj As String
    Public Property msgBody As String
    Public Property msgFromName As String
    Public Property msgFrom As String
    Public Property isHtml As Nullable(Of Boolean)
    Public Property attachmentName As String
    Public Property isSent As Nullable(Of Boolean)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property smtpServerAddress As String
    Public Property smtpLogin As String
    Public Property smtpPassword As String
    Public Property smtpPort As String

End Class
