'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Enquiry
    Public Property EnquiryID As Integer
    Public Property CareManagerAssignedID_FK As Nullable(Of Integer)
    Public Property EnquirySourceID_FK As Nullable(Of Integer)
    Public Property FirstName As String
    Public Property LastName As String
    Public Property DateOfBirth As Nullable(Of Date)
    Public Property RaceID_FK As Nullable(Of Integer)
    Public Property IdentificationNumber As String
    Public Property PreferredLanguageID_FK As Nullable(Of Integer)
    Public Property GenderID_FK As Nullable(Of Integer)
    Public Property PatientAddress1 As String
    Public Property PatientAddress2 As String
    Public Property PatientAddress3 As String
    Public Property PostalCode As String
    Public Property NameOfCaller As String
    Public Property ContactNumberOfCaller As String
    Public Property EmailOfCaller As String
    Public Property PreferredAppointmentDateTime As Nullable(Of Date)
    Public Property MedicalHistory As String
    Public Property CaregiverAtHomeID_FK As Nullable(Of Integer)
    Public Property ServicesRequiredID_FK As Nullable(Of Integer)
    Public Property Status As String
    Public Property Remarks As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Nullable(Of Boolean)
    Public Property OtherRace As String
    Public Property OtherPreferredLanguage As String
    Public Property UserOrganizationID_FK As Nullable(Of Integer)
    Public Property CaseNumber As String
    Public Property Note As String
    Public Property OrderID As String

    Public Overridable Property Code As Code
    Public Overridable Property Code1 As Code
    Public Overridable Property Code2 As Code
    Public Overridable Property Code3 As Code
    Public Overridable Property Code4 As Code
    Public Overridable Property Code5 As Code
    Public Overridable Property Code6 As Code
    Public Overridable Property Users As Users
    Public Overridable Property EnquiryAttachment As ICollection(Of EnquiryAttachment) = New HashSet(Of EnquiryAttachment)
    Public Overridable Property Code7 As ICollection(Of Code) = New HashSet(Of Code)
    Public Overridable Property Code8 As ICollection(Of Code) = New HashSet(Of Code)

End Class
