'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EventUserLog
    Public Property EventUserLogID As Integer
    Public Property EventID_FK As Integer
    Public Property UserID_FK As Integer
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean

    Public Overridable Property [Event] As [Event]
    Public Overridable Property Users As Users

End Class
