'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ExternalDoctor
    Public Property ExternalDoctorID As Integer
    Public Property Name As String
    Public Property ClinicianTypeID_FK As Nullable(Of Integer)
    Public Property Contact As String
    Public Property Email As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property AccessHospitalID_FK As Nullable(Of Integer)

    Public Overridable Property UserType As UserType
    Public Overridable Property PatientClinician As ICollection(Of PatientClinician) = New HashSet(Of PatientClinician)
    Public Overridable Property PatientWoundVisitClinician As ICollection(Of PatientWoundVisitClinician) = New HashSet(Of PatientWoundVisitClinician)

End Class
