'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InitialCareAssessment
    Public Property InitialCareAssessmentID As Integer
    Public Property PatientID_FK As Nullable(Of Integer)
    Public Property GeneralCondition As String
    Public Property Physique As String
    Public Property ConsciousLevel As String
    Public Property EmotionalState As String
    Public Property OtherEmotionalState As String
    Public Property Breathing As String
    Public Property OtherBreathing As String
    Public Property O2Litres As Nullable(Of Decimal)
    Public Property O2LitresVia As String
    Public Property TracheostomyDateInserted As Nullable(Of Date)
    Public Property TracheostomySize As String
    Public Property TracheostomyType As String
    Public Property IsTracheostomyInnerCannula As Nullable(Of Boolean)
    Public Property TracheostomyNextReviewDate As Nullable(Of Date)
    Public Property Cough As String
    Public Property Vision As String
    Public Property VisionImpairedLeft As Nullable(Of Boolean)
    Public Property VisionImpairedRight As Nullable(Of Boolean)
    Public Property VisionImpairedRemarks As String
    Public Property VisionImpairedGlaucoma As Nullable(Of Boolean)
    Public Property VisionImpairedCataract As Nullable(Of Boolean)
    Public Property VisionImpairedGlaucomaLeft As Nullable(Of Boolean)
    Public Property VisionImpairedGlaucomaRight As Nullable(Of Boolean)
    Public Property VisionImpairedGlaucomaRemarks As String
    Public Property VisionImpairedCataractLeft As Nullable(Of Boolean)
    Public Property VisionImpairedCataractRight As Nullable(Of Boolean)
    Public Property VisionImpairedCataractRemarks As String
    Public Property Hearing As String
    Public Property HearingImpairedLeft As Nullable(Of Boolean)
    Public Property HearingImpairedRight As Nullable(Of Boolean)
    Public Property HearingImpairedRemarks As String
    Public Property HearingImpairedWithHearingAidLeft As Nullable(Of Boolean)
    Public Property HearingImpairedWithHearingAidRight As Nullable(Of Boolean)
    Public Property HearingImpairedWithHearingAidRemarks As String
    Public Property BowelHabitsTimes As String
    Public Property BowelHabitsDays As String
    Public Property BowelType As String
    Public Property Stoma As String
    Public Property StomaCreatedDate As Nullable(Of Date)
    Public Property StomaSizeLength As Nullable(Of Decimal)
    Public Property StomaSizeBreath As Nullable(Of Decimal)
    Public Property StomaColour As String
    Public Property StomaAppearance As String
    Public Property StomaProtrusion As String
    Public Property StomaPeristomalSkin As String
    Public Property StomaEffluent As String
    Public Property StomaAmountOfOutput As String
    Public Property StomaOstomyProductUsed As String
    Public Property StomaReviewDate As Nullable(Of Date)
    Public Property UrinaryFrequencyTimes As String
    Public Property UrinaryFrequencyDay As String
    Public Property UrinaryTypes As String
    Public Property Catheter As String
    Public Property CatheterDateInserted As Nullable(Of Date)
    Public Property CatheterType As String
    Public Property CatheterSize As String
    Public Property CatheterNextReviewDate As Nullable(Of Date)
    Public Property LMP As Nullable(Of Date)
    Public Property UseOfDrug As Nullable(Of Boolean)
    Public Property UseOfDrugExplain As String
    Public Property MedicalHistory As String
    Public Property OralCavityAssessmentScore1 As Nullable(Of Integer)
    Public Property OralCavityAssessmentScore2 As Nullable(Of Integer)
    Public Property OralCavityAssessmentScore3 As Nullable(Of Integer)
    Public Property OralCavityAssessmentScore4 As Nullable(Of Integer)
    Public Property OralCavityAssessmentScore5 As Nullable(Of Integer)
    Public Property OralCavityAssessmentScore6 As Nullable(Of Integer)
    Public Property MilkFeedRx As String
    Public Property EmotionalYesNo As Nullable(Of Boolean)
    Public Property EmotionalYes As String
    Public Property HowCanIHelp As String
    Public Property LostInterest As Nullable(Of Boolean)
    Public Property LostInterestYes As String
    Public Property HowDoYouScope As String
    Public Property DifficultyCoping As Nullable(Of Boolean)
    Public Property DifficultyCopingYes As String
    Public Property Depressed As Nullable(Of Boolean)
    Public Property GetSupport As String
    Public Property ReferCounsellor As Nullable(Of Boolean)
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property Status As String
    Public Property PatientProfileID_FK As Nullable(Of Integer)
    Public Property PatientReferralID_FK As Nullable(Of Integer)
    Public Property SectionStatus As String
    Public Property PatientAdditionalInfoID_FK As Nullable(Of Integer)
    Public Property VitalSignID_FK As Nullable(Of Integer)
    Public Property WoundAssessmentScore1 As Nullable(Of Integer)
    Public Property WoundAssessmentScore2 As Nullable(Of Integer)
    Public Property WoundAssessmentScore3 As Nullable(Of Integer)
    Public Property WoundAssessmentScore4 As Nullable(Of Integer)
    Public Property WoundAssessmentScore5 As Nullable(Of Integer)
    Public Property WoundAssessmentScore6 As Nullable(Of Integer)
    Public Property PatientMedicationID_FK As Nullable(Of Integer)
    Public Property HomeFacilityVentilation As Nullable(Of Boolean)
    Public Property HomeFacilityCooking As Nullable(Of Boolean)
    Public Property HomeFacilityRefrigeration As Nullable(Of Boolean)
    Public Property HomeFacilityToileting As Nullable(Of Boolean)
    Public Property HomeFacilityStairs As Nullable(Of Boolean)
    Public Property HomeFacilityCommunication As Nullable(Of Boolean)
    Public Property HomeFacilityAffectCaregiver As Nullable(Of Boolean)
    Public Property HomeFacilityAffectCareManager As Nullable(Of Boolean)
    Public Property HomeFacilityRemarks As String
    Public Property IsRequirePalliativeCare As Nullable(Of Boolean)
    Public Property PainLevel As Nullable(Of Integer)
    Public Property TirednessLevel As Nullable(Of Integer)
    Public Property DrowsinessLevel As Nullable(Of Integer)
    Public Property NauseaLevel As Nullable(Of Integer)
    Public Property LackOfAppetiteLevel As Nullable(Of Integer)
    Public Property ShortnessOfBreath As Nullable(Of Integer)
    Public Property DepressionLevel As Nullable(Of Integer)
    Public Property AnxietyLevel As Nullable(Of Integer)
    Public Property BestWellbeing As Nullable(Of Integer)
    Public Property Faith As String
    Public Property IsReligious As Nullable(Of Boolean)
    Public Property GiveMeaningToLife As String
    Public Property MakeSense As String
    Public Property IsBeliefImportant As Nullable(Of Boolean)
    Public Property InfluenceTakeCare As String
    Public Property BeliefInfluenced As String
    Public Property RoleOfBeliefForInfluence As String
    Public Property IsPartOfCommunity As Nullable(Of Boolean)
    Public Property SupportTo As String
    Public Property RoleOfBeliefForCommunity As String
    Public Property PersonalConcern As String
    Public Property AddressIssue As String
    Public Property Concern As String
    Public Property TalkToSomeone As String
    Public Property OralCavityAssessmentScore7 As Nullable(Of Integer)
    Public Property OralCavityAssessmentScore8 As Nullable(Of Integer)
    Public Property PatientNutritionID_FK As Nullable(Of Integer)
    Public Property PatientRAFID_FK As Nullable(Of Integer)
    Public Property PatientMBIID_FK As Nullable(Of Integer)
    Public Property PatientMFSID_FK As Nullable(Of Integer)
    Public Property VisitDateTime As Nullable(Of Date)
    Public Property VSOnSetDate As Nullable(Of Date)
    Public Property painOnSetDate As Nullable(Of Date)
    Public Property VSQuality As String
    Public Property VSPainFrequency As String
    Public Property VSIntermittent As String
    Public Property VSLocation As String
    Public Property VSPrecipitatingFactors As String
    Public Property VSRelievingFactors As String
    Public Property VSPainFrequencyIntermittentNumber As Nullable(Of Integer)
    Public Property CAAlertness As String
    Public Property CACommunication As String
    Public Property CADementia As Nullable(Of Boolean)
    Public Property CAdateAndTime As Nullable(Of Boolean)
    Public Property CAPerson As Nullable(Of Boolean)
    Public Property CAPlace As Nullable(Of Boolean)
    Public Property CASituation As Nullable(Of Boolean)
    Public Property HearingAid As Nullable(Of Boolean)
    Public Property ChestSymmetry As Nullable(Of Boolean)
    Public Property AbdomenSymmetry As Nullable(Of Boolean)
    Public Property AnySkinIssue As Nullable(Of Boolean)
    Public Property PressureInjuries As Nullable(Of Boolean)
    Public Property ApicalPulse As Nullable(Of Integer)
    Public Property SkinType As String
    Public Property SkinIssue As String
    Public Property SkinTurgor As String
    Public Property BreathSounds As String
    Public Property BowelSounds As String
    Public Property Percussion As String
    Public Property Palpation As String
    Public Property TenderNGuarding As String
    Public Property Remark As String
    Public Property LeftUpperLimbStrength As Nullable(Of Integer)
    Public Property RightUpperLimbStrength As Nullable(Of Integer)
    Public Property LeftLowerLimbStrength As Nullable(Of Integer)
    Public Property RightLowerLimbStrength As Nullable(Of Integer)
    Public Property MobilityStatus As String
    Public Property AssistiveAids As String
    Public Property Incontinence As Nullable(Of Boolean)
    Public Property IncontinenceType As String
    Public Property UrineConsistency As String
    Public Property UrineColour As String
    Public Property StoolsType As String
    Public Property VisionSpectacles As Nullable(Of Boolean)
    Public Property OxygenRequired As Nullable(Of Boolean)
    Public Property Sputum As Nullable(Of Boolean)
    Public Property SuctioningRequired As Nullable(Of Boolean)
    Public Property OxygenLMin As Nullable(Of Decimal)
    Public Property OxygenType As String
    Public Property OxygenRemark As String
    Public Property Oralhealth As String
    Public Property Teeth As String
    Public Property AblePassUrine As Nullable(Of Boolean)
    Public Property NutritionalImbalance As Nullable(Of Boolean)

    Public Overridable Property PatientAdditionalInfo As PatientAdditionalInfo
    Public Overridable Property PatientMBI As PatientMBI
    Public Overridable Property PatientMedication As PatientMedication
    Public Overridable Property PatientMFS As PatientMFS
    Public Overridable Property PatientNutrition As PatientNutrition
    Public Overridable Property PatientProfile As PatientProfile
    Public Overridable Property PatientRAF As PatientRAF
    Public Overridable Property PatientReferral As PatientReferral
    Public Overridable Property VitalSigns As VitalSigns
    Public Overridable Property InitialCareAssessmentAttachment As ICollection(Of InitialCareAssessmentAttachment) = New HashSet(Of InitialCareAssessmentAttachment)
    Public Overridable Property InitialCareAssessmentSpecialInstruction As ICollection(Of InitialCareAssessmentSpecialInstruction) = New HashSet(Of InitialCareAssessmentSpecialInstruction)
    Public Overridable Property PatientAMT As ICollection(Of PatientAMT) = New HashSet(Of PatientAMT)
    Public Overridable Property PatientClinician As ICollection(Of PatientClinician) = New HashSet(Of PatientClinician)
    Public Overridable Property PatientDrugAllergy As ICollection(Of PatientDrugAllergy) = New HashSet(Of PatientDrugAllergy)
    Public Overridable Property PatientEBASDEP As ICollection(Of PatientEBASDEP) = New HashSet(Of PatientEBASDEP)
    Public Overridable Property PatientFamilyHistory As ICollection(Of PatientFamilyHistory) = New HashSet(Of PatientFamilyHistory)
    Public Overridable Property PatientOtherAllergy As ICollection(Of PatientOtherAllergy) = New HashSet(Of PatientOtherAllergy)
    Public Overridable Property PatientSocialSupport As ICollection(Of PatientSocialSupport) = New HashSet(Of PatientSocialSupport)
    Public Overridable Property PatientWound As ICollection(Of PatientWound) = New HashSet(Of PatientWound)
    Public Overridable Property PatientWoundVisit As ICollection(Of PatientWoundVisit) = New HashSet(Of PatientWoundVisit)
    Public Overridable Property Task As ICollection(Of Task) = New HashSet(Of Task)
    Public Overridable Property Code As ICollection(Of Code) = New HashSet(Of Code)

End Class
