'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IntegrationApiRequestLog
    Public Property IntegrationApiRequestLogID As Integer
    Public Property IntegrationSource As String
    Public Property FacilityId As String
    Public Property ResidentId As String
    Public Property Url As String
    Public Property Content As String
    Public Property Status As String
    Public Property CreatedByID_FK As Nullable(Of Integer)
    Public Property Timestamp As Nullable(Of Date)

End Class
