'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Item
    Public Property ItemID As Integer
    Public Property ItemName As String
    Public Property CategoryID_FK As Integer
    Public Property ItemUnitID_FK As Integer
    Public Property Quantity As Integer
    Public Property UnitPrice As Decimal
    Public Property AvailableInBilling As Nullable(Of Boolean)
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

    Public Overridable Property BillingInvoiceConsumable As ICollection(Of BillingInvoiceConsumable) = New HashSet(Of BillingInvoiceConsumable)
    Public Overridable Property Code As Code
    Public Overridable Property Code1 As Code
    Public Overridable Property ItemStock As ICollection(Of ItemStock) = New HashSet(Of ItemStock)
    Public Overridable Property PatientWoundVisitTreatment As ICollection(Of PatientWoundVisitTreatment) = New HashSet(Of PatientWoundVisitTreatment)

End Class
