'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MultiDisciplinaryMeeting
    Public Property MultiDisciplinaryMeetingID As Integer
    Public Property PatientID_FK As Integer
    Public Property IssuesOverall As String
    Public Property AssignedToFollowUp As Integer
    Public Property Remarks As String
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean

    Public Overridable Property Patient As Patient
    Public Overridable Property MultiDisciplinaryMeetingDetail As ICollection(Of MultiDisciplinaryMeetingDetail) = New HashSet(Of MultiDisciplinaryMeetingDetail)

End Class
