'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NotificationMessageTemplates
    Public Property id As Integer
    Public Property notificationgroupCode As String
    Public Property notificationSubject As String
    Public Property notificationMessage As String
    Public Property createdDate As Date
    Public Property updatedDate As Nullable(Of Date)

    Public Overridable Property Types As Types

End Class
