'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NotificationVitalSignDetails
    Public Property id As Integer
    Public Property notificationId As Integer
    Public Property createdDate As Date
    Public Property updatedDate As Nullable(Of Date)
    Public Property VitalSignDetailId As Integer

    Public Overridable Property Notifications As Notifications
    Public Overridable Property VitalSignDetails As VitalSignDetails

End Class
