'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NutritionTaskReference
    Public Property ReferenceID As Integer
    Public Property CodeId_FK As Integer
    Public Property ReferenceImage As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property Value As Nullable(Of Integer)

    Public Overridable Property Code As Code
    Public Overridable Property NutritionTask As ICollection(Of NutritionTask) = New HashSet(Of NutritionTask)
    Public Overridable Property NutritionTask1 As ICollection(Of NutritionTask) = New HashSet(Of NutritionTask)
    Public Overridable Property NutritionTask2 As ICollection(Of NutritionTask) = New HashSet(Of NutritionTask)

End Class
