'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientMedicationConsume
    Public Property PatientMedicationConsumeID As Integer
    Public Property PatientMedicationID_FK As Integer
    Public Property MedicationID_FK As Nullable(Of Integer)
    Public Property RouteID_FK As Nullable(Of Integer)
    Public Property DosageID_FK As Nullable(Of Integer)
    Public Property FrequencyID_FK As Nullable(Of Integer)
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Indication As String
    Public Property ReasonOfDiscontinue As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property ChronicDiseaseID_FK As Nullable(Of Integer)
    Public Property ChronicDiseaseSubInfoID_FK As Nullable(Of Integer)
    Public Property AcutePRNIndicationID_FK As Nullable(Of Integer)
    Public Property ReferID_FK As Nullable(Of Integer)
    Public Property InstructedByID_FK As Nullable(Of Integer)
    Public Property DrName As String
    Public Property DrContact As String
    Public Property MCRNo As String
    Public Property ClinicHosp As String
    Public Property InstructedBy2ID_FK As Nullable(Of Integer)
    Public Property DrNameED As String
    Public Property DrContactED As String
    Public Property MCRNoED As String
    Public Property ClinicHospED As String

    Public Overridable Property Code As Code
    Public Overridable Property Code1 As Code
    Public Overridable Property Code2 As Code
    Public Overridable Property Code3 As Code
    Public Overridable Property Code4 As Code
    Public Overridable Property Code5 As Code
    Public Overridable Property Code6 As Code
    Public Overridable Property Disease As Disease
    Public Overridable Property DiseaseSubInfo As DiseaseSubInfo
    Public Overridable Property PatientMedication As PatientMedication
    Public Overridable Property PatientMedicationConsume1 As ICollection(Of PatientMedicationConsume) = New HashSet(Of PatientMedicationConsume)
    Public Overridable Property PatientMedicationConsume2 As PatientMedicationConsume
    Public Overridable Property PatientMedicationConsumeAttachment As ICollection(Of PatientMedicationConsumeAttachment) = New HashSet(Of PatientMedicationConsumeAttachment)

End Class
