'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Patient
    Public Property PatientID As Integer
    Public Property Firstname As String
    Public Property Lastname As String
    Public Property NRIC As String
    Public Property DateOfBirth As Nullable(Of Date)
    Public Property Age As Nullable(Of Integer)
    Public Property PostalCode As String
    Public Property Photo As String
    Public Property CareManagerAssignedID As Nullable(Of Integer)
    Public Property CaseID As String
    Public Property DrugAllergy As String
    Public Property Status As String
    Public Property DischargeNoticePeriodInMonths As Nullable(Of Integer)
    Public Property AdmittedDate As Nullable(Of Date)
    Public Property ReasonOfAdmission As String
    Public Property AMD As Nullable(Of Boolean)
    Public Property ACP As Nullable(Of Boolean)
    Public Property PACEMAKER As Nullable(Of Boolean)
    Public Property ACID As Nullable(Of Boolean)
    Public Property MobilePhone As String
    Public Property HomePhone As String
    Public Property Email As String
    Public Property GenogramPicture As String
    Public Property ReferringDiagnosis As String
    Public Property MailForVitalAlert1 As String
    Public Property MailForVitalAlert2 As String
    Public Property MailForVitalAlert3 As String
    Public Property MailForFamilyNotification1 As String
    Public Property MailForFamilyNotification2 As String
    Public Property VisitingFrequency As String
    Public Property NumberOfChildren As Nullable(Of Integer)
    Public Property Occupation As String
    Public Property UpfrontPayment As Nullable(Of Boolean)
    Public Property CareReviewDate As Nullable(Of Date)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property PatientTypeID_FK As Nullable(Of Integer)
    Public Property MailingAddress1 As String
    Public Property MailingAddress2 As String
    Public Property MailingAddress3 As String
    Public Property GenderID_FK As Nullable(Of Integer)
    Public Property BloodTypeID_FK As Nullable(Of Integer)
    Public Property ResidentTypeID_FK As Nullable(Of Integer)
    Public Property MaritalStatusID_FK As Nullable(Of Integer)
    Public Property ReligionID_FK As Nullable(Of Integer)
    Public Property PatientProfileID_FK As Nullable(Of Integer)
    Public Property RaceID_FK As Nullable(Of Integer)
    Public Property PatientAdditionalInfoID_FK As Nullable(Of Integer)
    Public Property PatientReferralID_FK As Nullable(Of Integer)
    Public Property MedicalHistoryRemarks As String
    Public Property PatientMedicationID_FK As Nullable(Of Integer)
    Public Property PatientReferralByID_FK As Nullable(Of Integer)
    Public Property IdentificationNumber As String
    Public Property IdentificationAttachmentFilename As String
    Public Property IdentificationAttachmentPhysical As String
    Public Property OtherRace As String
    Public Property OtherLanguage As String
    Public Property PaymentMode As String
    Public Property InvoiceModeID_FK As Nullable(Of Integer)
    Public Property DisplayName As String
    Public Property OrderID As String
    Public Property Accepted As Nullable(Of Boolean)
    Public Property NursingStation As String
    Public Property AccessHospitalID_FK As Nullable(Of Integer)
    Public Property ActionDescription As String
    Public Property IntegrationSourceID As String

    Public Overridable Property BillingInvoice As ICollection(Of BillingInvoice) = New HashSet(Of BillingInvoice)
    Public Overridable Property BillingProposal As ICollection(Of BillingProposal) = New HashSet(Of BillingProposal)
    Public Overridable Property CarePlan As ICollection(Of CarePlan) = New HashSet(Of CarePlan)
    Public Overridable Property CareReport As ICollection(Of CareReport) = New HashSet(Of CareReport)
    Public Overridable Property Chat As ICollection(Of Chat) = New HashSet(Of Chat)
    Public Overridable Property Code As Code
    Public Overridable Property Code1 As Code
    Public Overridable Property Code2 As Code
    Public Overridable Property Code3 As Code
    Public Overridable Property Code4 As Code
    Public Overridable Property Code5 As Code
    Public Overridable Property Code6 As Code
    Public Overridable Property Code7 As Code
    Public Overridable Property Code8 As Code
    Public Overridable Property MultiDisciplinaryMeeting As ICollection(Of MultiDisciplinaryMeeting) = New HashSet(Of MultiDisciplinaryMeeting)
    Public Overridable Property NutritionTask As ICollection(Of NutritionTask) = New HashSet(Of NutritionTask)
    Public Overridable Property PatientAdditionalInfo As PatientAdditionalInfo
    Public Overridable Property PatientMedication As PatientMedication
    Public Overridable Property PatientProfile As PatientProfile
    Public Overridable Property PatientReferral As PatientReferral
    Public Overridable Property PatientAMT As ICollection(Of PatientAMT) = New HashSet(Of PatientAMT)
    Public Overridable Property PatientAttachment As ICollection(Of PatientAttachment) = New HashSet(Of PatientAttachment)
    Public Overridable Property PatientClinician As ICollection(Of PatientClinician) = New HashSet(Of PatientClinician)
    Public Overridable Property PatientDrugAllergy As ICollection(Of PatientDrugAllergy) = New HashSet(Of PatientDrugAllergy)
    Public Overridable Property PatientEBASDEP As ICollection(Of PatientEBASDEP) = New HashSet(Of PatientEBASDEP)
    Public Overridable Property PatientFamilyHistory As ICollection(Of PatientFamilyHistory) = New HashSet(Of PatientFamilyHistory)
    Public Overridable Property PatientImmunisation As ICollection(Of PatientImmunisation) = New HashSet(Of PatientImmunisation)
    Public Overridable Property PatientMedicalHistory As ICollection(Of PatientMedicalHistory) = New HashSet(Of PatientMedicalHistory)
    Public Overridable Property PatientOtherAllergy As ICollection(Of PatientOtherAllergy) = New HashSet(Of PatientOtherAllergy)
    Public Overridable Property PatientSocialSupport As ICollection(Of PatientSocialSupport) = New HashSet(Of PatientSocialSupport)
    Public Overridable Property PatientWound As ICollection(Of PatientWound) = New HashSet(Of PatientWound)
    Public Overridable Property PatientWoundDraft As ICollection(Of PatientWoundDraft) = New HashSet(Of PatientWoundDraft)
    Public Overridable Property Receipt As ICollection(Of Receipt) = New HashSet(Of Receipt)
    Public Overridable Property RecentView As ICollection(Of RecentView) = New HashSet(Of RecentView)
    Public Overridable Property Task As ICollection(Of Task) = New HashSet(Of Task)
    Public Overridable Property TeleconsultationRecording As ICollection(Of TeleconsultationRecording) = New HashSet(Of TeleconsultationRecording)
    Public Overridable Property Users As ICollection(Of Users) = New HashSet(Of Users)
    Public Overridable Property VitalSignRelationships As ICollection(Of VitalSignRelationships) = New HashSet(Of VitalSignRelationships)
    Public Overridable Property VitalSigns As ICollection(Of VitalSigns) = New HashSet(Of VitalSigns)
    Public Overridable Property Facility As ICollection(Of Facility) = New HashSet(Of Facility)
    Public Overridable Property Code9 As ICollection(Of Code) = New HashSet(Of Code)
    Public Overridable Property Package As ICollection(Of Package) = New HashSet(Of Package)
    Public Overridable Property Code10 As ICollection(Of Code) = New HashSet(Of Code)

End Class
