'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientClinician
    Public Property PatientClinicianID As Integer
    Public Property PatientID_FK As Nullable(Of Integer)
    Public Property InitialCareAssessmentID_FK As Nullable(Of Integer)
    Public Property UserID_FK As Nullable(Of Integer)
    Public Property ExternalDoctorID_FK As Nullable(Of Integer)
    Public Property DiseaseID_FK As Nullable(Of Integer)
    Public Property DiseaseSubInfoID_FK As Nullable(Of Integer)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean

    Public Overridable Property CareReportSystemInfo As ICollection(Of CareReportSystemInfo) = New HashSet(Of CareReportSystemInfo)
    Public Overridable Property CareReportSystemInfo1 As ICollection(Of CareReportSystemInfo) = New HashSet(Of CareReportSystemInfo)
    Public Overridable Property Disease As Disease
    Public Overridable Property DiseaseSubInfo As DiseaseSubInfo
    Public Overridable Property ExternalDoctor As ExternalDoctor
    Public Overridable Property InitialCareAssessment As InitialCareAssessment
    Public Overridable Property Patient As Patient
    Public Overridable Property Users As Users
    Public Overridable Property PatientMedicalHistory As ICollection(Of PatientMedicalHistory) = New HashSet(Of PatientMedicalHistory)
    Public Overridable Property PatientReferral As ICollection(Of PatientReferral) = New HashSet(Of PatientReferral)
    Public Overridable Property PatientReferral1 As ICollection(Of PatientReferral) = New HashSet(Of PatientReferral)
    Public Overridable Property PatientReferral2 As ICollection(Of PatientReferral) = New HashSet(Of PatientReferral)
    Public Overridable Property PatientReferral3 As ICollection(Of PatientReferral) = New HashSet(Of PatientReferral)

End Class
