'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientMedication
    Public Property PatientMedicationID As Integer
    Public Property Allergies As String
    Public Property SelfAdminister As Nullable(Of Boolean)
    Public Property Compliant As Nullable(Of Boolean)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean

    Public Overridable Property InitialCareAssessment As ICollection(Of InitialCareAssessment) = New HashSet(Of InitialCareAssessment)
    Public Overridable Property Patient As ICollection(Of Patient) = New HashSet(Of Patient)
    Public Overridable Property PatientMedicationConsume As ICollection(Of PatientMedicationConsume) = New HashSet(Of PatientMedicationConsume)
    Public Overridable Property Code As ICollection(Of Code) = New HashSet(Of Code)

End Class
