'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientWoundDraftTreatmentList
    Public Property PatientWoundDraftTListID As Integer
    Public Property PatientWoundDraftID_FK As Integer
    Public Property TListItemID_FK As Integer
    Public Property Remarks As String
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

    Public Overridable Property PatientWoundDraft As PatientWoundDraft
    Public Overridable Property TreatmentListItem As TreatmentListItem

End Class
