'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientEBASDEP
    Public Property PatientEBASDEPID As Integer
    Public Property PatientID_FK As Nullable(Of Integer)
    Public Property InitialCareAssessmentID_FK As Nullable(Of Integer)
    Public Property Alertness As String
    Public Property Score As Nullable(Of Integer)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property CareReportID_FK As Nullable(Of Integer)
    Public Property VitalSignDetailId_FK As Nullable(Of Integer)

    Public Overridable Property CareReport As CareReport
    Public Overridable Property InitialCareAssessment As InitialCareAssessment
    Public Overridable Property Patient As Patient
    Public Overridable Property VitalSignDetails As VitalSignDetails
    Public Overridable Property PatientEBASDEPAnswer As ICollection(Of PatientEBASDEPAnswer) = New HashSet(Of PatientEBASDEPAnswer)

End Class
