'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientWoundVisitTreatment
    Public Property PatientWoundVisitTreatmentID As Integer
    Public Property PatientWoundVisitID_FK As Integer
    Public Property ItemID_FK As Integer
    Public Property Quantity As Integer
    Public Property IsChargeable As Boolean
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

    Public Overridable Property Item As Item
    Public Overridable Property PatientWoundVisit As PatientWoundVisit

End Class
