'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientAMTAnswer
    Public Property PatientAMTID_FK As Integer
    Public Property AMTQuestionID_FK As Integer
    Public Property Answer As Nullable(Of Integer)

    Public Overridable Property AMTQuestion As AMTQuestion
    Public Overridable Property PatientAMT As PatientAMT

End Class
