'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientNutrition
    Public Property PatientNutritionID As Integer
    Public Property EatingAndSwallowing As String
    Public Property EatingAndSwallowingTypeOfTubeFeeding As String
    Public Property EatingAndSwallowingTypeOfTube As String
    Public Property EatingAndSwallowingSize As String
    Public Property EatingAndSwallowingDateInserted As Nullable(Of Date)
    Public Property EatingAndSwallowingDateDue As Nullable(Of Date)
    Public Property Diet As String
    Public Property Appetite As String
    Public Property FluidConsistency As String
    Public Property FluidRestrictionMLSPerDay As Nullable(Of Decimal)
    Public Property ReviewedBySpeechTherapist As Nullable(Of Boolean)
    Public Property ReferralToSpeechTherapist As Nullable(Of Boolean)
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property Enteralfeeding As String
    Public Property SizeofPEGJtube As String
    Public Property IVtherapyStateType As String
    Public Property SwallowingIssues As Nullable(Of Boolean)
    Public Property DiagnosedDysphasia As Nullable(Of Boolean)
    Public Property IsFIsluidRestriction As Nullable(Of Boolean)
    Public Property IVtherapy As Nullable(Of Boolean)
    Public Property IVtherapyMLSPerDay As Nullable(Of Decimal)
    Public Property MilkFeedAmt As Nullable(Of Decimal)
    Public Property WaterPerDay As Nullable(Of Decimal)
    Public Property DiagnosedDysphasiaLastReviewDate As Nullable(Of Date)

    Public Overridable Property CareReport As ICollection(Of CareReport) = New HashSet(Of CareReport)
    Public Overridable Property InitialCareAssessment As ICollection(Of InitialCareAssessment) = New HashSet(Of InitialCareAssessment)

End Class
