'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProblemListGoal
    Public Property ProblemListGoalID As Integer
    Public Property ProblemListID_FK As Integer
    Public Property Goal As String
    Public Property Action As Nullable(Of Integer)
    Public Property ScoreTypeID As Nullable(Of Integer)
    Public Property OperatorID As Nullable(Of Integer)

    Public Overridable Property CarePlanSubProblemListGoal As ICollection(Of CarePlanSubProblemListGoal) = New HashSet(Of CarePlanSubProblemListGoal)
    Public Overridable Property Code As Code
    Public Overridable Property Code1 As Code
    Public Overridable Property ProblemList As ProblemList

End Class
