'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ResidentAssessmentCategory
    Public Property ResidentAssessmentCategoryID As Integer
    Public Property Category1Description As String
    Public Property Category1Recommendation As String
    Public Property Category2Description As String
    Public Property Category2Recommendation As String
    Public Property Category3Description As String
    Public Property Category3Recommendation As String
    Public Property Category4Description As String
    Public Property Category4Recommendation As String
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

End Class
