'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Resource
    Public Property ResourceId As Integer
    Public Property CodeId As Integer
    Public Property LanguageId As Integer
    Public Property CodeValue As String
    Public Property Details As String

    Public Overridable Property Code As Code
    Public Overridable Property Language As Language

End Class
