-- Database: C4WX1

-- DROP DATABASE IF EXISTS "C4WX1";

CREATE DATABASE "C4WX1"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_Malaysia.1252'
    LC_CTYPE = 'English_Malaysia.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Table: public.ErrorLog

-- DROP TABLE IF EXISTS public."ErrorLog";

CREATE TABLE IF NOT EXISTS public."ErrorLog"
(
    "ErrorLogId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ErrorDetails" text COLLATE pg_catalog."default" NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ErrorLog" PRIMARY KEY ("ErrorLogId")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."ErrorLog"
    OWNER to postgres;