'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SyncPatientLog
    Public Property SyncLogId As Integer
    Public Property SyncBatchTs As Integer
    Public Property PatientID As Integer
    Public Property OffPatientID As Integer
    Public Property ServerPatientID As Nullable(Of Integer)
    Public Property SyncResult As Boolean
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Nullable(Of Integer)

End Class
