'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Task
    Public Property TaskID As Integer
    Public Property ActionTypeID_FK As Integer
    Public Property PatientID_FK As Nullable(Of Integer)
    Public Property InitialCareAssessmentID_FK As Nullable(Of Integer)
    Public Property Description As String
    Public Property Remarks As String
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Location As String
    Public Property OtherLocation As String
    Public Property FrequencyID_FK As Nullable(Of Integer)
    Public Property DosageID_FK As Nullable(Of Integer)
    Public Property MilkFeedVolumeMLS As Nullable(Of Decimal)
    Public Property Supplement As String
    Public Property H2OFlushingMLS As Nullable(Of Decimal)
    Public Property ReferenceType As String
    Public Property ReferenceID As Nullable(Of Integer)
    Public Property Pending As Nullable(Of Boolean)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property MedicationID_FK As Nullable(Of Integer)
    Public Property Recurrence_Frequency As Nullable(Of Integer)
    Public Property Recurrence_Days As Nullable(Of Integer)
    Public Property Recurrence_Interval As Nullable(Of Integer)
    Public Property Recurrence_IntervalFlag As Nullable(Of Integer)
    Public Property MedicationInstructions As String
    Public Property recurrenceDailyHourly As Nullable(Of Integer)
    Public Property UserCategory_FK As Nullable(Of Integer)

    Public Overridable Property Code As Code
    Public Overridable Property Code1 As Code
    Public Overridable Property Code2 As Code
    Public Overridable Property Code3 As Code
    Public Overridable Property InitialCareAssessment As InitialCareAssessment
    Public Overridable Property NotificationTask As ICollection(Of NotificationTask) = New HashSet(Of NotificationTask)
    Public Overridable Property Patient As Patient
    Public Overridable Property UserCategory As UserCategory
    Public Overridable Property Users As Users
    Public Overridable Property TaskFileAttachment As ICollection(Of TaskFileAttachment) = New HashSet(Of TaskFileAttachment)
    Public Overridable Property TaskSpecificDate As ICollection(Of TaskSpecificDate) = New HashSet(Of TaskSpecificDate)
    Public Overridable Property TaskUser As ICollection(Of TaskUser) = New HashSet(Of TaskUser)
    Public Overridable Property TaskUserLog As ICollection(Of TaskUserLog) = New HashSet(Of TaskUserLog)
    Public Overridable Property Code4 As ICollection(Of Code) = New HashSet(Of Code)

End Class
