'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Types
    Public Property code As String
    Public Property codeValue As String
    Public Property parentCode As String
    Public Property ordering As Integer
    Public Property created As Date
    Public Property updated As Nullable(Of Date)

    Public Overridable Property APIAccessKey As ICollection(Of APIAccessKey) = New HashSet(Of APIAccessKey)
    Public Overridable Property NotificationMessageTemplates As ICollection(Of NotificationMessageTemplates) = New HashSet(Of NotificationMessageTemplates)
    Public Overridable Property Notifications As ICollection(Of Notifications) = New HashSet(Of Notifications)
    Public Overridable Property Types1 As ICollection(Of Types) = New HashSet(Of Types)
    Public Overridable Property Types2 As Types

End Class
