'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserType
    Public Property UserTypeID As Integer
    Public Property UserType1 As String
    Public Property UserCategoryID_FK As Integer
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property ManpowerRate As Nullable(Of Decimal)

    Public Overridable Property CareReportConfig As ICollection(Of CareReportConfig) = New HashSet(Of CareReportConfig)
    Public Overridable Property ExternalDoctor As ICollection(Of ExternalDoctor) = New HashSet(Of ExternalDoctor)
    Public Overridable Property UserCategory As UserCategory
    Public Overridable Property MailSettings As ICollection(Of MailSettings) = New HashSet(Of MailSettings)
    Public Overridable Property Users As ICollection(Of Users) = New HashSet(Of Users)

End Class
