'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Users
    Public Property UserId As Integer
    Public Property Email As String
    Public Property Password As String
    Public Property Firstname As String
    Public Property Lastname As String
    Public Property Remarks As String
    Public Property Photo As String
    Public Property Contact As String
    Public Property Designation As String
    Public Property Status As String
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property LastLoginDate As Nullable(Of Date)
    Public Property LastLogoutDate As Nullable(Of Date)
    Public Property LastActivityDate As Nullable(Of Date)
    Public Property LastLockoutDate As Nullable(Of Date)
    Public Property LastPasswordChangedDate As Nullable(Of Date)
    Public Property PreviousPasswords As String
    Public Property SessionKey As String
    Public Property ResetPassword As Nullable(Of Boolean)
    Public Property IsDeleted As Boolean
    Public Property LocationNow1 As String
    Public Property LocationNow2 As String
    Public Property LocationNow3 As String
    Public Property PostalCodeNow As String
    Public Property LocationNowModifiedDate As Nullable(Of Date)
    Public Property PatientID_FK As Nullable(Of Integer)
    Public Property IsExternal As Boolean
    Public Property UserOrganizationID_FK As Nullable(Of Integer)
    Public Property IsTCAccepted As Nullable(Of Boolean)
    Public Property UserName As String
    Public Property PreferredLanguage As Nullable(Of Integer)
    Public Property AccessLevelID_FK As Nullable(Of Integer)
    Public Property HasValidEmail As Boolean
    Public Property TokenID As String
    Public Property PreviousPasswords2 As String
    Public Property SharePdf As Nullable(Of Boolean)

    Public Overridable Property AuditTrail As ICollection(Of AuditTrail) = New HashSet(Of AuditTrail)
    Public Overridable Property BillingInvoice As ICollection(Of BillingInvoice) = New HashSet(Of BillingInvoice)
    Public Overridable Property BillingInvoice1 As ICollection(Of BillingInvoice) = New HashSet(Of BillingInvoice)
    Public Overridable Property BillingProposal As ICollection(Of BillingProposal) = New HashSet(Of BillingProposal)
    Public Overridable Property BillingProposal1 As ICollection(Of BillingProposal) = New HashSet(Of BillingProposal)
    Public Overridable Property CareReport As ICollection(Of CareReport) = New HashSet(Of CareReport)
    Public Overridable Property CareReportSystemInfo As ICollection(Of CareReportSystemInfo) = New HashSet(Of CareReportSystemInfo)
    Public Overridable Property CareReportSystemInfo1 As ICollection(Of CareReportSystemInfo) = New HashSet(Of CareReportSystemInfo)
    Public Overridable Property Chat As ICollection(Of Chat) = New HashSet(Of Chat)
    Public Overridable Property Enquiry As ICollection(Of Enquiry) = New HashSet(Of Enquiry)
    Public Overridable Property EnquiryConfig As ICollection(Of EnquiryConfig) = New HashSet(Of EnquiryConfig)
    Public Overridable Property EnquiryConfig1 As ICollection(Of EnquiryConfig) = New HashSet(Of EnquiryConfig)
    Public Overridable Property [Event] As ICollection(Of [Event]) = New HashSet(Of [Event])
    Public Overridable Property EventUser As ICollection(Of EventUser) = New HashSet(Of EventUser)
    Public Overridable Property EventUserLog As ICollection(Of EventUserLog) = New HashSet(Of EventUserLog)
    Public Overridable Property MobileAppVersioning As ICollection(Of MobileAppVersioning) = New HashSet(Of MobileAppVersioning)
    Public Overridable Property MobileAppVersioning1 As ICollection(Of MobileAppVersioning) = New HashSet(Of MobileAppVersioning)
    Public Overridable Property Notifications As ICollection(Of Notifications) = New HashSet(Of Notifications)
    Public Overridable Property Patient As Patient
    Public Overridable Property PatientClinician As ICollection(Of PatientClinician) = New HashSet(Of PatientClinician)
    Public Overridable Property PatientWoundReviewBy As ICollection(Of PatientWoundReviewBy) = New HashSet(Of PatientWoundReviewBy)
    Public Overridable Property PatientWoundVisit As ICollection(Of PatientWoundVisit) = New HashSet(Of PatientWoundVisit)
    Public Overridable Property PatientWoundVisitClinician As ICollection(Of PatientWoundVisitClinician) = New HashSet(Of PatientWoundVisitClinician)
    Public Overridable Property Receipt As ICollection(Of Receipt) = New HashSet(Of Receipt)
    Public Overridable Property Receipt1 As ICollection(Of Receipt) = New HashSet(Of Receipt)
    Public Overridable Property RecentView As ICollection(Of RecentView) = New HashSet(Of RecentView)
    Public Overridable Property Task As ICollection(Of Task) = New HashSet(Of Task)
    Public Overridable Property TaskUser As ICollection(Of TaskUser) = New HashSet(Of TaskUser)
    Public Overridable Property TaskUserLog As ICollection(Of TaskUserLog) = New HashSet(Of TaskUserLog)
    Public Overridable Property UserAddress As ICollection(Of UserAddress) = New HashSet(Of UserAddress)
    Public Overridable Property UserRole As ICollection(Of UserRole) = New HashSet(Of UserRole)
    Public Overridable Property EnquiryConfig2 As ICollection(Of EnquiryConfig) = New HashSet(Of EnquiryConfig)
    Public Overridable Property EnquiryConfig3 As ICollection(Of EnquiryConfig) = New HashSet(Of EnquiryConfig)
    Public Overridable Property Branch As ICollection(Of Branch) = New HashSet(Of Branch)
    Public Overridable Property Code As ICollection(Of Code) = New HashSet(Of Code)
    Public Overridable Property Code1 As ICollection(Of Code) = New HashSet(Of Code)
    Public Overridable Property Code2 As ICollection(Of Code) = New HashSet(Of Code)
    Public Overridable Property UserType As ICollection(Of UserType) = New HashSet(Of UserType)

End Class
