'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserRole
    Public Property UserId_FK As Integer
    Public Property RoleId_FK As Integer
    Public Property Role As String

    Public Overridable Property Role1 As Role
    Public Overridable Property Users As Users

End Class
