'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserCategory
    Public Property UserCategoryID As Integer
    Public Property UserCategory1 As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)
    Public Property IsDeleted As Boolean
    Public Property UserCategoryOrganizationID_FK As Nullable(Of Integer)
    Public Property EnableGeoFencing As Nullable(Of Boolean)

    Public Overridable Property Code As Code
    Public Overridable Property [Event] As ICollection(Of [Event]) = New HashSet(Of [Event])
    Public Overridable Property Task As ICollection(Of Task) = New HashSet(Of Task)
    Public Overridable Property UserCategoryRole As ICollection(Of UserCategoryRole) = New HashSet(Of UserCategoryRole)
    Public Overridable Property UserType As ICollection(Of UserType) = New HashSet(Of UserType)
    Public Overridable Property Facility As ICollection(Of Facility) = New HashSet(Of Facility)
    Public Overridable Property UserCategory11 As ICollection(Of UserCategory) = New HashSet(Of UserCategory)
    Public Overridable Property UserCategory2 As ICollection(Of UserCategory) = New HashSet(Of UserCategory)

End Class
