'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VitalSignTypeThreshold
    Public Property VitalSignTypeID_FK As Integer
    Public Property ews_min_1 As Nullable(Of Decimal)
    Public Property ews_max_1 As Nullable(Of Decimal)
    Public Property ews_min_2 As Nullable(Of Decimal)
    Public Property ews_max_2 As Nullable(Of Decimal)
    Public Property ews_min_3 As Nullable(Of Decimal)
    Public Property ews_max_3 As Nullable(Of Decimal)
    Public Property ews_min_4 As Nullable(Of Decimal)
    Public Property ews_max_4 As Nullable(Of Decimal)
    Public Property ews_min_5 As Nullable(Of Decimal)
    Public Property ews_max_5 As Nullable(Of Decimal)
    Public Property ews_min_6 As Nullable(Of Decimal)
    Public Property ews_max_6 As Nullable(Of Decimal)
    Public Property ews_min_7 As Nullable(Of Decimal)
    Public Property ews_max_7 As Nullable(Of Decimal)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy_FK As Nullable(Of Integer)
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

    Public Overridable Property VitalSignTypes As VitalSignTypes

End Class
