'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VitalSigns
    Public Property id As Integer
    Public Property patientId As Integer
    Public Property source As String
    Public Property icaId As Integer
    Public Property isDeleted As Boolean
    Public Property createdBy As Nullable(Of Integer)
    Public Property createdDate As Date
    Public Property updatedBy As Nullable(Of Integer)
    Public Property updatedDate As Nullable(Of Date)

    Public Overridable Property CareReport As ICollection(Of CareReport) = New HashSet(Of CareReport)
    Public Overridable Property InitialCareAssessment As ICollection(Of InitialCareAssessment) = New HashSet(Of InitialCareAssessment)
    Public Overridable Property Patient As Patient
    Public Overridable Property PatientWoundVisit As ICollection(Of PatientWoundVisit) = New HashSet(Of PatientWoundVisit)
    Public Overridable Property VitalSignDetails As ICollection(Of VitalSignDetails) = New HashSet(Of VitalSignDetails)

End Class
