'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VitalSignRelationships
    Public Property id As Integer
    Public Property vitalSignTypeId As Integer
    Public Property patientId As Integer
    Public Property thresholdId As Integer

    Public Overridable Property Patient As Patient
    Public Overridable Property Thresholds As Thresholds
    Public Overridable Property VitalSignTypes As VitalSignTypes

End Class
