'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VitalSignTypes
    Public Property id As Integer
    Public Property name As String
    Public Property isDeleted As Boolean
    Public Property createdBy As Nullable(Of Integer)
    Public Property createdDate As Date
    Public Property updatedBy As Nullable(Of Integer)
    Public Property updatedDate As Nullable(Of Date)

    Public Overridable Property DiseaseVitalSignType As ICollection(Of DiseaseVitalSignType) = New HashSet(Of DiseaseVitalSignType)
    Public Overridable Property MedicationVitalSignType As ICollection(Of MedicationVitalSignType) = New HashSet(Of MedicationVitalSignType)
    Public Overridable Property VitalSignDetails As ICollection(Of VitalSignDetails) = New HashSet(Of VitalSignDetails)
    Public Overridable Property VitalSignRelationships As ICollection(Of VitalSignRelationships) = New HashSet(Of VitalSignRelationships)
    Public Overridable Property VitalSignTypeThreshold As VitalSignTypeThreshold

End Class
