'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WoundConsolidatedEmail
    Public Property WoundConsolidatedEmailID As Integer
    Public Property PatientWoundVisitID_FK As Integer
    Public Property MailSettingsID_FK As Integer
    Public Property PDFContent As String
    Public Property IsDeleted As Boolean
    Public Property CreatedDate As Date
    Public Property CreatedBy_FK As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy_FK As Nullable(Of Integer)

    Public Overridable Property MailSettings As MailSettings
    Public Overridable Property PatientWoundVisit As PatientWoundVisit

End Class
